from fm_mapping import (
    GLS_90, NP_XG_90, SHOT_90, SHOT_R, XA_90, CH_C_90, OP_KP_90,
    OP_CR_R, OP_CRS_A_90, DRB_90, PAS_R, PS_A_90, PR_PASSES_90,
    PR_PASSES_R, POSS_WON_90, POSS_LOST_90, DEF_ACT_C_90, PRES_R, PRES_A_90,
    HDR_R, AER_A_90, INVERTED_PERCENTILE_FIELDS, PER90_PERCENTILE_STANDARD_STATS, PER90_PERCENTILE_SHOOTING_STATS,
    PER90_PERCENTILE_PASSING_STATS, PER90_PERCENTILE_DEFENDING_STATS, PER90_PERCENTILE_POSSESSION_STATS,
    PER90_PERCENTILE_MISC_STATS, CENTERBACK, FULLBACK, MIDFIELDER, ATT_MID_WINGER, FORWARD
)

FONT_NORMAL_FILE = 'https://raw.githubusercontent.com/googlefonts/roboto/main/src/hinted/Roboto-Regular.ttf'
FONT_ITALIC_FILE = 'https://raw.githubusercontent.com/googlefonts/roboto/main/src/hinted/Roboto-Italic.ttf'
FONT_BOLD_FILE = 'https://raw.githubusercontent.com/google/fonts/main/apache/robotoslab/RobotoSlab[wght].ttf'

DEFAULT_SELECTED_METRICS = [
    GLS_90, NP_XG_90, SHOT_90, SHOT_R, XA_90, CH_C_90, OP_KP_90,
    OP_CR_R, OP_CRS_A_90, DRB_90, PAS_R, PS_A_90, PR_PASSES_90,
    PR_PASSES_R, POSS_WON_90, POSS_LOST_90, DEF_ACT_C_90, PRES_R, PRES_A_90,
    HDR_R, AER_A_90
]

POSITION_GROUPS = (
    CENTERBACK, FULLBACK, MIDFIELDER, ATT_MID_WINGER, FORWARD
)

PER90_PERCENTILE_STATS_GROUPS = (
    PER90_PERCENTILE_STANDARD_STATS,
    PER90_PERCENTILE_SHOOTING_STATS,
    PER90_PERCENTILE_PASSING_STATS,
    PER90_PERCENTILE_DEFENDING_STATS,
    PER90_PERCENTILE_POSSESSION_STATS,
    PER90_PERCENTILE_MISC_STATS,
)
