nonnumeric_fields_to_cc = {
    'Age': 'age',
    'Best Pos': 'best_pos',
    'Club': 'club',
    'Division': 'division',
    'Inf': 'inf',
    'Name': 'name',
    'Nat': 'nat',
    'Position': 'position',
    'Preferred Foot': 'preferred_foot',
    'Rec': 'rec',
    'Salary': 'salary',
    'Transfer Value': 'transfer_value',
    'UID': 'uid'
}

numeric_fields_to_cc = {
    'Aer A/90': 'aer_a_90',
    'Ast': 'ast',
    'Asts/90': 'asts_90',
    'Av Rat': 'av_rat',
    'Blk/90': 'blk_90',
    'Ch C/90': 'ch_c_90',
    'Clr/90': 'clr_90',
    'Conv %': 'conv_r',
    'Distance': 'dist',
    'Dist/90': 'dist_90',
    'Drb/90': 'drb_90',
    'FA': 'fa',
    'Fls': 'fls',
    'Gl Mst': 'gl_mst',
    'Gls': 'gls',
    'Gls/90': 'gls_90',
    'Hdr %': 'hdr_r',
    'Hdrs L/90': 'hdrs_l_90',
    'Hdrs W/90': 'hdrs_w_90',
    'Height': 'height',
    'Int/90': 'int_90',
    'K Hdrs/90': 'k_hdrs_90',
    'K Tck/90': 'k_tck_90',
    'Mins': 'mins',
    'NP-xG/90': 'np_xg_90',
    'OP-Cr %': 'op_cr_r',
    'OP-Crs A/90': 'op_crs_a_90',
    'OP-Crs C/90': 'op_crs_c_90',
    'OP-KP/90': 'op_kp_90',
    'Pas %': 'pas_r',
    'Pens S': 'pen_s',
    'Pens': 'pens',
    'Pen/R': 'pens_r',
    'Poss Lost/90': 'poss_lost_90',
    'Poss Won/90': 'poss_won_90',
    'Pr passes/90': 'pr_passes_90',
    'Pres A/90': 'pres_a_90',
    'Pres C/90': 'pres_c_90',
    'Ps A/90': 'ps_a_90',
    'Ps C/90': 'ps_c_90',
    'Shot %': 'shot_r',
    'Shot/90': 'shot_90',
    'Sprints/90': 'sprints_90',
    'Tck A': 'tck_a',
    'Tck W': 'tck_w',
    'Tck R': 'tck_r',
    'Tck/90': 'tck_90',
    'Tcon/90': 'tcon_90',
    'Tgls/90': 'tgls_90',
    'Weight': 'weight',
    'xA': 'xa',
    'xA/90': 'xa_90',
    'xG': 'xg',
    'xG/90': 'xg_90',
    'xG-OP': 'xg_op',
}

nonnumeric_cc_to_fields = {
    'age': 'Age',
    'best_pos': 'Best Pos',
    'club': 'Club',
    'division': 'Division',
    'name': 'Name',
    'nat': 'Nat',
    'position': 'Position',
    'preferred_foot': 'Preferred Foot',
    'salary': 'Salary',
    'transfer_value': 'Transfer Value',
}

numeric_cc_to_fields = {
    'aer_a_90': 'Aer A/90',
    'ast': 'Ast',
    'asts_90': 'Asts/90',
    'av_rat': 'Av Rat',
    'blk_90': 'Blk/90',
    'ch_c_90': 'Ch C/90',
    'clr_90': 'Clr/90',
    'conv_r': 'Conv %',
    'dist': 'Distance',
    'dist_90': 'Dist/90',
    'drb_90': 'Drb/90',
    'fa': 'FA',
    'fls': 'Fls',
    'gl_mst': 'Gl Mst',
    'gls': 'Gls',
    'gls_90': 'Gls/90',
    'hdr_r': 'Hdr %',
    'hdrs_l_90': 'Hdrs L/90',
    'hdrs_w_90': 'Hdrs W/90',
    'height': 'Height',
    'int_90': 'Int/90',
    'k_hdrs_90': 'K Hdrs/90',
    'k_tck_90': 'K Tck/90',
    'mins': 'Mins',
    'np_xg_90': 'NP-xG/90',
    'op_cr_r': 'OP-Cr %',
    'op_crs_a_90': 'OP-Crs A/90',
    'op_crs_c_90': 'OP-Crs C/90',
    'op_kp_90': 'OP-KP/90',
    'pas_r': 'Pas %',
    'pen_s': 'Pens S',
    'pens': 'Pens',
    'pens_r': 'Pen/R',
    'poss_lost_90': 'Poss Lost/90',
    'poss_won_90': 'Poss Won/90',
    'pr_passes_90': 'Pr passes/90',
    'pres_a_90': 'Pres A/90',
    'pres_c_90': 'Pres C/90',
    'ps_a_90': 'Ps A/90',
    'ps_c_90': 'Ps C/90',
    'shot_r': 'Shot %',
    'shot_90': 'Shot/90',
    'sprints_90': 'Sprints/90',
    'tck_a': 'Tck A',
    'tck_r': 'Tck R',
    'tck_w': 'Tck W',
    'tck_90': 'Tck/90',
    'tcon_90': 'Tcon/90',
    'tgls_90': 'Tgls/90',
    'weight': 'Weight',
    'xa': 'xA',
    'xa_90': 'xA/90',
    'xg': 'xG',
    'xg_90': 'xG/90',
    'xg_op': 'xG-OP',
}